#!/bin/bash

mac=$1

dev_list=$(ls /sys/class/net)

for dev in $dev_list; do
    if [ -e "/sys/class/net/$dev/device" ]; then
        if [ -e "/sys/class/net/$dev/device/sriov_numvfs" ]; then
            numvfs=$(cat /sys/class/net/$dev/device/sriov_numvfs)
            if (( $numvfs > 0 )); then
                ip link show $dev | grep $mac > /dev/null 2>&1
                if (( $? == 0 )); then
                    break
                fi
            fi
        fi
    fi
done

remote_dev=$(lldptool -i $dev get-tlv -n | grep -A 1 "System Name TLV" | \
        awk "/^[[:space:]]/"'{print $1}')

remote_port=$(lldptool -i $dev get-tlv -n | grep -A 1 "Port ID TLV" | \
        awk "/^[[:space:]]/"'{print $2}')

echo {\"local-port\": \"$dev\", \"remote-device\": \"$remote_dev\", \
        \"remote-port\": \"$remote_port\"}

exit 0

