#!/bin/sh

id_to_name()
{
    curl -s -u admin:contrail123 -H "Content-Type: application/json" -d "
    {
        \"uuid\": \"$1\"
    }" http://localhost:8095/id-to-fqname
}

id_to_name "$@"
exit 0

