#!/bin/sh

auth_url=192.168.189.142:35357/v2.0
username=admin
password=p@ssw0rd
tenant=admin

get_token()
{
    token=$(curl -s -H "Content-Type: application/json" -d "
    {
    \"auth\": {
        \"passwordCredentials\": {
            \"username\": \"$username\",
            \"password\": \"$password\"
        },
        \"tenantName\": \"$tenant\"
    }
    }"  http://$auth_url/tokens | python -c "import json; import sys; print json.load(sys.stdin)[\"access\"][\"token\"][\"id\"]" 2>/dev/null)
}

list_tenants()
{
    curl -s -H "X-Auth-Token: $token" http://$auth_url/tenants | python -m json.tool
}

get_token
echo $token
list_tenants

